INSERT INTO "Skills" ("Name")
VALUES
  -- Языки программирования
  ('C'),
  ('C++'),
  ('C#'),
  ('Java'),
  ('Kotlin'),
  ('Scala'),
  ('Groovy'),
  ('JavaScript'),
  ('TypeScript'),
  ('Python'),
  ('Go'),
  ('Rust'),
  ('Swift'),
  ('Objective-C'),
  ('PHP'),
  ('Ruby'),
  ('Perl'),
  ('R'),
  ('MATLAB'),
  ('Dart'),
  ('Lua'),
  ('Haskell'),
  ('Elixir'),
  ('Erlang'),
  ('F#'),
  ('Visual Basic .NET'),
  ('Delphi'),
  ('Assembler'),
  ('Bash'),
  ('PowerShell'),
  ('SQL'),
  ('PL/pgSQL'),
  ('T-SQL'),
  ('HTML'),
  ('CSS'),
  ('Sass'),
  ('SCSS'),
  ('Less'),
  ('XML'),
  ('JSON'),
  ('YAML'),
  ('Markdown'),

  -- Frontend
  ('React'),
  ('Next.js'),
  ('Vue.js'),
  ('Nuxt.js'),
  ('Angular'),
  ('Svelte'),
  ('SvelteKit'),
  ('jQuery'),
  ('Redux'),
  ('Redux Toolkit'),
  ('MobX'),
  ('Zustand'),
  ('RxJS'),
  ('Webpack'),
  ('Vite'),
  ('Parcel'),
  ('Babel'),
  ('ESLint'),
  ('Prettier'),
  ('Tailwind CSS'),
  ('Bootstrap'),
  ('Material UI'),
  ('Ant Design'),
  ('Chakra UI'),
  ('Shadcn UI'),
  ('Styled Components'),
  ('Emotion'),
  ('Framer Motion'),

  -- Backend / .NET
  ('ASP.NET'),
  ('ASP.NET Core'),
  ('ASP.NET MVC'),
  ('ASP.NET Web API'),
  ('Blazor'),
  ('Entity Framework'),
  ('Entity Framework Core'),
  ('Dapper'),
  ('LINQ'),
  ('WPF'),
  ('Windows Forms'),
  ('MAUI'),
  ('Xamarin'),
  ('SignalR'),
  ('MediatR'),
  ('AutoMapper'),
  ('FluentValidation'),
  ('Serilog'),
  ('NLog'),
  ('Log4Net'),
  ('MassTransit'),
  ('Ocelot'),

  -- Java / JVM
  ('Spring'),
  ('Spring Boot'),
  ('Spring MVC'),
  ('Spring Web'),
  ('Spring Data JPA'),
  ('Spring Security'),
  ('Hibernate'),
  ('Jakarta EE'),
  ('Java EE'),
  ('Maven'),
  ('Gradle'),
  ('JUnit'),
  ('Mockito'),
  ('Logback'),
  ('SLF4J'),
  ('Lombok'),
  ('MapStruct'),
  ('Quarkus'),
  ('Micronaut'),

  -- JavaScript / TypeScript backend
  ('Node.js'),
  ('Express'),
  ('NestJS'),
  ('Fastify'),
  ('Koa'),
  ('Socket.IO'),
  ('Prisma'),
  ('TypeORM'),
  ('Sequelize'),
  ('Mongoose'),

  -- Python
  ('Django'),
  ('Django REST Framework'),
  ('Flask'),
  ('FastAPI'),
  ('Pydantic'),
  ('SQLAlchemy'),
  ('Alembic'),
  ('Celery'),
  ('Pandas'),
  ('NumPy'),
  ('SciPy'),
  ('Matplotlib'),
  ('Seaborn'),
  ('Plotly'),
  ('Scikit-learn'),
  ('TensorFlow'),
  ('Keras'),
  ('PyTorch'),
  ('OpenCV'),
  ('Beautiful Soup'),
  ('Scrapy'),
  ('Selenium'),

  -- PHP
  ('Laravel'),
  ('Symfony'),
  ('CodeIgniter'),
  ('Yii'),
  ('Composer'),

  -- Ruby
  ('Ruby on Rails'),
  ('Sinatra'),

  -- Go
  ('Gin'),
  ('Echo'),
  ('Fiber'),
  ('GORM'),

  -- Mobile
  ('Android'),
  ('Android SDK'),
  ('Jetpack Compose'),
  ('XML Layouts'),
  ('Retrofit'),
  ('Room'),
  ('Coroutines'),
  ('Flutter'),
  ('React Native'),
  ('Ionic'),
  ('Capacitor'),

  -- API / интеграции
  ('REST API'),
  ('RESTful Services'),
  ('GraphQL'),
  ('gRPC'),
  ('OpenAPI'),
  ('Swagger'),
  ('Swagger UI'),
  ('Postman'),
  ('Insomnia'),
  ('WebSocket'),
  ('SOAP'),
  ('JWT'),
  ('OAuth 2.0'),
  ('OpenID Connect'),

  -- Базы данных
  ('PostgreSQL'),
  ('MySQL'),
  ('MariaDB'),
  ('SQLite'),
  ('Microsoft SQL Server'),
  ('Oracle Database'),
  ('MongoDB'),
  ('Redis'),
  ('Cassandra'),
  ('Elasticsearch'),
  ('OpenSearch'),
  ('Firebase Realtime Database'),
  ('Cloud Firestore'),
  ('Neo4j'),
  ('InfluxDB'),
  ('DynamoDB'),
  ('Cosmos DB'),

  -- ORM / Data access
  ('JPA'),
  ('Hibernate ORM'),
  ('MyBatis'),
  ('ADO.NET'),
  ('JDBC'),
  ('ODBC'),

  -- DevOps / контейнеризация / CI/CD
  ('Git'),
  ('GitHub'),
  ('GitLab'),
  ('Bitbucket'),
  ('Git Flow'),
  ('Docker'),
  ('Docker Compose'),
  ('Kubernetes'),
  ('Helm'),
  ('OpenShift'),
  ('Podman'),
  ('Nginx'),
  ('Apache HTTP Server'),
  ('Traefik'),
  ('HAProxy'),
  ('Jenkins'),
  ('GitHub Actions'),
  ('GitLab CI/CD'),
  ('Azure DevOps'),
  ('TeamCity'),
  ('CircleCI'),
  ('Travis CI'),
  ('Terraform'),
  ('Ansible'),
  ('Vagrant'),
  ('Packer'),

  -- Облачные платформы
  ('AWS'),
  ('Microsoft Azure'),
  ('Google Cloud Platform'),
  ('Firebase'),
  ('Heroku'),
  ('Netlify'),
  ('Vercel'),
  ('Cloudflare'),

  -- Очереди / брокеры / стриминг
  ('Kafka'),
  ('Apache Kafka'),
  ('RabbitMQ'),
  ('ActiveMQ'),
  ('Redis Pub/Sub'),
  ('Amazon SQS'),
  ('Apache Pulsar'),
  ('ZeroMQ'),

  -- Тестирование
  ('Unit Testing'),
  ('Integration Testing'),
  ('End-to-End Testing'),
  ('xUnit'),
  ('NUnit'),
  ('MSTest'),
  ('JUnit 5'),
  ('TestNG'),
  ('Pytest'),
  ('Unittest'),
  ('Jest'),
  ('Mocha'),
  ('Chai'),
  ('Vitest'),
  ('Cypress'),
  ('Playwright'),
  ('Selenium WebDriver'),
  ('Appium'),
  ('Mockito'),
  ('MockK'),
  ('WireMock'),

  -- Архитектура / подходы
  ('OOP'),
  ('SOLID'),
  ('Design Patterns'),
  ('Clean Architecture'),
  ('Microservices'),
  ('Monolithic Architecture'),
  ('Event-Driven Architecture'),
  ('Domain-Driven Design'),
  ('CQRS'),
  ('Event Sourcing'),
  ('MVC'),
  ('MVVM'),
  ('MVP'),
  ('Repository Pattern'),
  ('Unit of Work'),
  ('Dependency Injection'),

  -- Аналитика / Data / AI
  ('Data Analysis'),
  ('Data Science'),
  ('Machine Learning'),
  ('Deep Learning'),
  ('Computer Vision'),
  ('Natural Language Processing'),
  ('ETL'),
  ('Apache Spark'),
  ('Hadoop'),
  ('Airflow'),
  ('Jupyter'),
  ('Google Colab'),

  -- Безопасность
  ('Cybersecurity'),
  ('Application Security'),
  ('OWASP'),
  ('Authentication'),
  ('Authorization'),
  ('IdentityServer'),
  ('Keycloak'),

  -- Системы / ОС / сети
  ('Linux'),
  ('Ubuntu'),
  ('Debian'),
  ('CentOS'),
  ('Windows Server'),
  ('Networking'),
  ('TCP/IP'),
  ('DNS'),
  ('HTTP'),
  ('HTTPS'),
  ('SSH'),

  -- Мониторинг / логирование
  ('Prometheus'),
  ('Grafana'),
  ('Kibana'),
  ('ELK Stack'),
  ('Loki'),
  ('Jaeger'),

  -- Инструменты разработки
  ('Visual Studio'),
  ('Visual Studio Code'),
  ('IntelliJ IDEA'),
  ('Rider'),
  ('PyCharm'),
  ('WebStorm'),
  ('Android Studio'),
  ('DataGrip'),
  ('Figma'),

  -- CMS / платформы / прочее
  ('WordPress'),
  ('Shopify'),
  ('1C'),
  ('SAP'),
  ('CRM Systems'),
  ('ERP Systems'),

  -- Дополнительные популярные технологии
  ('WebRTC'),
  ('Three.js'),
  ('Electron'),
  ('Tauri'),
  ('PWA'),
  ('SSR'),
  ('CSR'),
  ('SSG'),
  ('BEM'),
  ('Responsive Design'),
  ('Cross-Browser Compatibility'),
  ('Accessibility'),
  ('i18n'),
  ('l10n')
ON CONFLICT ("Name") DO NOTHING;